### PR TITLE
Use SwiftLocation instead of Location

### PR DESCRIPTION
**Pull request by brightsider**
Please, accept this PR.
When I've in project object Location, I've conflict with your library :(

### CODE REVIEW

**Comment by brightsider** [comment]
Or maybe you can make Location/SwiftLocation via some flag 👍

**Comment by Alex293** [comment]
+1

**Comment by malcommac** [comment]
You can use SwiftLocation.Location to avoid conflicts.

**Comment by brightsider** [comment]
@malcommac Thanks, it's working.

**Pull request closed without merging**
