### PR TITLE
Converted to Swift 2

### PR DESCRIPTION
**Pull request by evermeer**

### CODE REVIEW

**Comment by malcommac** [comment]
Thank you :)

**Comment by evermeer** [comment]
You're welcome. I am now using it in my demo app swift 2 branch. I replaced WherAmI for SwiftLocation.

You can find it here:
https://github.com/evermeer/EVCloudKitDao/blob/Swift2/AppMessage/AppMessage/Controlers/ChatViewController.swift#L300

**Comment by malcommac** [comment]
Great :-) I'm glad for that. This give me an idea; I could start a list of apps/libraries which uses SwiftLocation into the readme file. Can I add your EVCloudKitDao?

**Comment by evermeer** [comment]
Sure :-) 
SwiftLocation is already in my readme (swift2 branch)

**Pull request merged**
