### PR TITLE
Swift 4 and Xcode 9 compatible

### PR DESCRIPTION
**Pull request by hamzaansari09**
- Fix void error on onStartMonitoring
- Remove redundant Equatable protocol in Request protocol

### CODE REVIEW

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.

**Comment by otymartin** [comment]
@malcommac can't install the latest 3.0.1 through cocoa pods. 
i did pod 'SwiftLocation', '3.0.1-beta' doesn't work

**Comment by ercancelik** [comment]
@otymartin use `pod 'SwiftLocation', :git => 'https://github.com/malcommac/SwiftLocation.git'`

**Comment by otymartin** [comment]
@ercancelik thanks problem was I already had 'SwiftyJSON' whereas 'SwiftLocation' also has 'SwiftyJSON' as a dependency so it was causing a conflict. Had to remove my 'SwiftyJSON' for it to work.

**Pull request closed without merging**
